Fix stats checking feature and add more asserts
ercdndrs/AutoMaxLair pull request #70
Opened 2021-03-08 19:03 UTC by pifopi

Also fix some linting errors
Fix the den scrolling by shortening it a bit

2021-03-09 21:48 UTC, ercdndrs reviewed
Looks good!

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +        return self.current_run.balls[ball_id].names[self.lang]
It seems like the full ball name will be returned. Would it be possible to cut out the "Ball" part of the name? Or is that hard to do in a language-agnostic way?

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/ball.py
> +    """Represent a ball. Contains one id and one translation for each language"""
```suggestion
    """Represents a ball. Contains one id and names in multiple languages."""
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/ball.py
> +        self.names = names
```suggestion
        self.names = names

    def __str__(self) -> str:
        return self.name_id
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.base_balls <= 999, 'Too much base ball'
```suggestion
            assert self.base_balls <= 999, 'Too many base balls.'
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.base_balls >= 4, 'Not enough base ball'
```suggestion
            assert self.base_balls >= 4, 'Not enough base balls.'
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.base_balls >= 3, 'Not enough base ball'
```suggestion
            assert self.base_balls >= 3, 'Not enough base balls.'
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.base_balls <= 999, 'Too much base ball'
```suggestion
            assert self.base_balls <= 999, 'Too many base balls.'
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.legendary_balls >= 1, 'Not enough legendary ball'
```suggestion
            assert self.legendary_balls >= 1, 'Not enough legendary balls.'
```

2021-03-09 21:48 UTC, ercdndrs commented on automaxlair/da_controller.py
> +            assert self.legendary_balls <= 999, 'Too much legendary ball'
```suggestion
            assert self.legendary_balls <= 999, 'Too many legendary balls.'
```

2021-03-10 15:25 UTC, ercdndrs requested changes
Again nice work! There was one thing regarding default balls that might need to be changed. See my comment in auto_max_lair.py.

2021-03-10 15:25 UTC, ercdndrs commented on auto_max_lair.py
> +    ctrlr.push_button(b'8', 2 + VIDEO_EXTRA_DELAY, 7)
Do you find 7 works better?

2021-03-10 15:25 UTC, ercdndrs commented on auto_max_lair.py
> +    while (ctrlr.get_target_ball() not in ctrlr.check_ball()):
What happens when the target ball is `default`? It seems to me like the bot might get stuck looping through balls forever trying to find "Default balls".

2021-03-10 15:25 UTC, ercdndrs commented on automaxlair/max_lair_instance.py
> +        with open(data_paths[6], 'r', encoding='utf8') as file:
Not a big deal, but the balls can probably be stored in the DAController since they don't need to be refreshed every run.

2021-03-10 17:45 UTC, pifopi commented on auto_max_lair.py
> +    ctrlr.push_button(b'8', 2 + VIDEO_EXTRA_DELAY, 7)
on my side, yes ! they're almost perfectly centered with 7. But if that's only on my side, I can revert and have the change locally only.
You never got the warning about facing the wrong type of pokemon ?

2021-03-10 17:46 UTC, pifopi commented on auto_max_lair.py
> +    while (ctrlr.get_target_ball() not in ctrlr.check_ball()):
right now, it will assert because default is not on the list of available balls. But I can add it back

2021-03-10 17:58 UTC, pifopi commented on automaxlair/max_lair_instance.py
> +        with open(data_paths[6], 'r', encoding='utf8') as file:
done !

2021-03-10 19:38 UTC, ercdndrs commented on auto_max_lair.py
> +    ctrlr.push_button(b'8', 2 + VIDEO_EXTRA_DELAY, 7)
Yeah, I know we were looking for a solution so glad you found one.

2021-03-10 19:39 UTC, ercdndrs commented on auto_max_lair.py
> +    while (ctrlr.get_target_ball() not in ctrlr.check_ball()):
Oh, so if you want to use Poke balls you put that in? That works better actually. It means you won't use rarer balls if you put in the numbers wrong.

2021-03-10 19:39 UTC, ercdndrs approved these changes

2021-03-10 19:46 UTC, merged